services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  # TODO: add your code here (delete this line and follow the indent conventions)
  app:
    # TODO: you will need to add to this
    build: ./backend
    ports:
      - "9900:9900"
    environment:
      - REDIS_HOST=redis
  frontend:
    # TODO: you will need to add to this
    build: ./frontend
    ports:
      - "3901:3000" # mapping the external port 3333 to container's internal port 3000 (on your computer use localhost:3333)
    depends_on:
      - app # this depends on the backend container (which we called web at the top of this file)
